services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  app-python:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      localstack: 
        condition: service_healthy
    environment:
      AWS_ACCESS_KEY_ID: 'test'
      AWS_SECRET_ACCESS_KEY: 'test'
      REGION: us-east-1
      DYNAMODB_ENDPOINT: http://localstack:4566
      S3_ENDPOINT: http://localstack:4566
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  test-runner:
    build:
      context: .
      dockerfile: tests/Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      app-python:
        condition: service_healthy
    profiles: [test]
    environment:
      BASE_URL: http://app-python:8080
    command: pytest -q tests