version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
  app-python:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: app-python
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
      - localstack
    environment:
      AWS_ACCESS_KEY_ID:    'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      REGION:               'us-east-1'
      DYNAMODB_ENDPOINT:    'http://dynamodb-local:8000'
      S3_ENDPOINT:          'http://localstack:4566'
networks:
  default:
    external:
      name: "localstack"